/* autogenerated by Processing revision 1293 on 2024-12-13 */
import processing.core.*;
import processing.data.*;
import processing.event.*;
import processing.opengl.*;

import java.util.HashMap;
import java.util.ArrayList;
import java.io.File;
import java.io.BufferedReader;
import java.io.PrintWriter;
import java.io.InputStream;
import java.io.OutputStream;
import java.io.IOException;

public class Universe_DD_Sketch extends PApplet {

//Space Universe Dear Diary Sketch
class Planet {
  String name;
  float distance;  
  float x, y;      
  int planetColor;
  int observationDays;  


  Planet(String name, float distance, int planetColor) {
    this.name = name;
    this.distance = distance;
    this.planetColor = planetColor;
    this.x = random(width);
    this.y = random(height);
    this.observationDays = 0;  
  }

  public void display() {
    fill(planetColor);
    noStroke();
    float size = map(distance, 384400, 78340000, 10, 200); 
    ellipse(x, y, size, size);
    
 
    textSize(20);
    fill(255);
    textAlign(CENTER, CENTER);
    text(name, x, y + size / 2 + 10);
    text("Days Observed: " + observationDays, x, y + size / 2 + 30);
  }

 
  public void update() {
    x += random(-1, 1); 
    y += random(-1, 1); 
  }


  public void incrementObservation() {
    observationDays++;
  }
}

Planet moon;
Planet mars;
Planet venus;

public void setup() {
  /* size commented out by preprocessor */;

  moon = new Planet("Moon", 384400, color(200, 200, 255)); 
  mars = new Planet("Mars", 78340000, color(255, 100, 100)); 
  venus = new Planet("Venus", 41400000, color(255, 255, 100)); 
}

public void draw() {
  background(0); 
  

  moon.display();
  mars.display();
  venus.display();
  

  moon.update();
  mars.update();
  venus.update();
  

  stroke(255);
  line(width / 2, height, moon.x, moon.y);
  line(width / 2, height, mars.x, mars.y);
  line(width / 2, height, venus.x, venus.y);
}


public void mousePressed() {
  
  float moonDist = dist(mouseX, mouseY, moon.x, moon.y);
  float marsDist = dist(mouseX, mouseY, mars.x, mars.y);
  float venusDist = dist(mouseX, mouseY, venus.x, venus.y);
  

  if (moonDist < marsDist && moonDist < venusDist) {
    moon.incrementObservation();
  } else if (marsDist < moonDist && marsDist < venusDist) {
    mars.incrementObservation();
  } else {
    venus.incrementObservation();
  }
}


  public void settings() { size(800, 800); }

  static public void main(String[] passedArgs) {
    String[] appletArgs = new String[] { "Universe_DD_Sketch" };
    if (passedArgs != null) {
      PApplet.main(concat(appletArgs, passedArgs));
    } else {
      PApplet.main(appletArgs);
    }
  }
}
